test/unit-test/CMakeLists.txt
CMake is updated to log test results after running the coverage target
=> Log test results after running the coverage target

test/cbmc/proofs/findHeaderFieldParserCallback/findHeaderFieldParserCallback_harness.c, test/cbmc/sources/http_cbmc_state.c, test/cbmc/stubs/HTTPClient_Send_http_parser_execute.c
Some proofs assume that some pointers returned by malloc are not
NULL. This patch modifies those proofs to make these assumptions
explicit with `__CPROVER_assume(pointer != NULL)` for all such
pointers.
=> Modify CBMC proofs to make assumptions about malloc explicit.

docs/doxygen/pages.dox, source/portable/transport_interface.h, test/unit-test/core_http_send_utest.c
This follows changes from [https://github.com/FreeRTOS/coreMQTT/pull/86](https://github.com/FreeRTOS/coreMQTT/pull/86) & [https://github.com/FreeRTOS/FreeRTOS/commit/398abbaa6199a12377a6254b197ab12f9788cc32](https://github.com/FreeRTOS/FreeRTOS/commit/398abbaa6199a12377a6254b197ab12f9788cc32). The const qualifier is removed from send/recv because there are transport implementations that require a member of the network context to be modified such as in the case of mbedtls.
=> Remove const qualifier from send/recv in transport interface

source/core_http_client.c, source/include/core_http_client.h, test/cbmc/sources/http_cbmc_state.c, test/unit-test/core_http_utest.c
- The title says it all.
- This parameters was missed somehow... and no one said anything... and we kept using it EVERYWHERE! AGH!
**Next steps:**  
Update submodule in CSDK and update usage everywhere there in all integ tests and demos.
=> Update HTTPRequestInfo_t.method to HTTPRequestInfo_t.pMethod for consistency

lexicon.txt, source/core_http_client.c, source/include/core_http_client.h, source/include/core_http_config_defaults.h, test/unit-test/core_http_send_utest.c, test/unit-test/core_http_utest.c
The enums in the HTTP Client library were following the CSDK v4_beta style upon initial development. The enum style then was to make them all caps because they are constants.
The [new style guide](https://docs.aws.amazon.com/freertos/latest/lib-ref/embedded-csdk/202009.00/lib-ref/docs/doxygen/output/html/guide_developer_styleguide.html) directs enum values for libraries to be in camel case. 
This PR updates all of the status enums for consistency.
**Next steps:**  
Update submodule in CSDK and update usage everywhere there in all integ tests and demos.
=> Change enum values from all uppercase to camel case for consistency

lexicon.txt, source/core_http_client.c, test/cbmc/proofs/HTTPClient_AddHeader/HTTPClient_AddHeader_harness.c, test/cbmc/proofs/HTTPClient_AddHeader/Makefile, test/cbmc/proofs/HTTPClient_AddRangeHeader/Makefile, test/cbmc/proofs/HTTPClient_InitializeRequestHeaders/Makefile, test/cbmc/proofs/HTTPClient_Send/Makefile, test/cbmc/stubs/strncpy.c, test/cbmc/stubs/transport_interface_stubs.c, test/unit-test/core_http_send_utest.c
This PR fixes some outstanding issues found by Coverity MISRA. After this PR there will be only 45 rule violations in the core_http_client.c source, all of which are related to using non-compliant http-parser.
This includes:
- Making explicit casts in comparisons for size_t against a narrower type.
- Delete unnecessary comparison that was just a work around for cbmc's transport interface send stub.
- Change all memcpy to strncpy for MISRA rule 7.4.
[cov-out.zip](https://github.com/FreeRTOS/coreHTTP/files/5436854/cov-out.zip)
=> Fix some issues found by Coverity MISRA

source/core_http_client.c, source/include/core_http_client.h, test/unit-test/core_http_utest.c
According to rfc 2616 It is not invalid to have an empty value for some header field.
http-parser will invoke the onHeaderValue callback with a length of zero when the header value is empty for a header field.
This commit updates the HTTPClient_ReadHeader function to return success if the header field is found, but the header value happens to be empty.
=> Update HTTPClient_ReadHeader to allow empty header values

source/core_http_client.c
Move all missed pointer dereferences to after asserts on NULL.
Add some missing asserts.
=> HTTP Client library assert hygiene 

source/core_http_client.c
- This variable is unused in httpParserOnMessageBeginCallback() and httpParserOnHeaderValueCallback().
=> Delete unused pResponse from some http-parser callbacks

.gitmodules, test/unit-test/cmock_build.cmake
Disable submodule cloning of **CMock** and **CBMC** submodules with the `git submodule update` command to improve cloning experience of the `aws/aws-iot-device-sdk-for-embedded-c` repository that submodules this repository. The pupose is to avoid duplicate cloning of leaf submodules from multiple repositories submoduled by C-SDK
=> Disable default cloning support of CMock and CBMC submodules

.github/workflows/manual.yml, .github/workflows/release.yml, source/interface/transport_interface.h
**Add a GitHub Action job to trigger a release process** which includes operations of: 
1. Creating and pushing the release tag to the repository 
2. Verifying the pushed tag (performing a diff with the commit ID which is tagged) 
3. Creating a ZIP for the release asset. 
4. Verifying the ZIP by performing a diff check and running unit tests on the unzipped files. 5. Creating a release on the repository for the tag, and uploading the ZIP as the release asset
The workflow can be manually triggered and takes the input values of **Commit ID** (to create a release for) and the **Version string** for tagging the release with
**Testing**
Here is an example run of the release job on my fork repository: 
https://github.com/aggarw13/coreHTTP/runs/1512507665?check_suite_focus=true
It pushed the …
=> Automate release with GitHub Action job

lexicon.txt, source/interface/transport_interface.h
Satisfy the **ssot-check** CI check for `transport_interface.h` file by updating it to match the latest from [FreeRTOS/coreMQTT](https://github.com/FreeRTOS/coreMQTT) repository.
=> Update transport_interface.h to match coreMQTT

lexicon.txt, source/interface/transport_interface.h
Sync transport interface header with coreMQTT, which is the SSoT for transport_interface.h
=> Sync transport interface with coreMQTT

docs/doxygen/pages.dox
Make coreHTTP memory numbers consistent with other libraries.
For example: https://docs.aws.amazon.com/embedded-csdk/202011.00/lib-ref/libraries/standard/coreMQTT/docs/doxygen/output/html/index.html#mqtt_memory_requirements
=> Make coreHTTP memory numbers consistent with other libraries

docs/doxygen/pages.dox, lexicon.txt, source/core_http_client.c, source/include/core_http_client.h, source/include/core_http_config_defaults.h, source/interface/transport_interface.h, test/cbmc/include/core_http_config.h, test/cbmc/include/get_time_stub.h, test/cbmc/proofs/HTTPClient_Send/HTTPClient_Send_harness.c, test/cbmc/proofs/HTTPClient_Send/Makefile, test/cbmc/stubs/get_time_stub.c, test/unit-test/core_http_config.h, test/unit-test/core_http_send_utest.c
This PR implements send and receive timeouts for HTTPClient_Send() just as coreMQTT does for MQTT_ProcessLoop and MQTT_RecieveLoop did here: https://github.com/FreeRTOS/coreMQTT/pull/120
This extra layer of protection allows receiving or sending data after small interrupts in the transport layer.
Before, *sendHttpData()* had the potential to loop forever which would be devastating in a single threaded environment.
Before, receiving the response would stop as soon as zero was returned from the transport receive. Zero was updated in the transport_interface.h file to mean "no data available right now". We want to try again, if the application desires, for a bit more robustness.
=> Implement transport send and receive timeouts in coreHTTP

docs/doxygen/pages.dox
We recently made a major update to add transport send and receive retry timeouts.
This updates the memory estimates in Doxygen.
The estimates are lower for the optimization builds because in the last release I forgot to add -DNDEBUG to the C flags while compiling.
=> Update the memory estimates table for latest changes.

CHANGELOG.md
Also call out not being backwards compatible.
=> Update changelog to be more concise

docs/doxygen/pages.dox
Sync the memory numbers with the numbers in Freertos.org at https://www.freertos.org/http/index.html
=> Sync the memory numbers with the numbers in FRO.

.github/workflows/memory_statistics.yml, docs/doxygen/config.doxyfile, docs/doxygen/include/size_table.html, docs/doxygen/pages.dox
Adds a manual workflow that calls the memory statistics action to generate a size table.
Additionally refactors the doxygen table into its own file to make updating it easier.
=> Add workflow to generate doxygen size tables

source/core_http_client.c, test/cbmc/proofs/findHeaderFieldParserCallback/Makefile
According to [RFC7230 Section 3.2](https://tools.ietf.org/html/rfc7230#section-3.2), parsing of HTTP header should be **case-insensitive**.
```text
3.2.  Header Fields
Each header field consists of a case-insensitive field name followed
by a colon (":"), optional leading whitespace, the field value, and
optional trailing whitespace.
```
If referring to obsolete [RFC2616 Section4.2](https://tools.ietf.org/html/rfc2616#section-4.2)
```text
Each header field consists of a name followed by a colon (":") and the field value. Field names
are case-insensitive.
```
If referring to Hypertext Transfer Protocol Version 2 (HTTP/2) [RFC7540 Section 8.1.2](https://tools.ietf.org/html/rfc7540#section-8.1.2)
```text
Just as in HTTP/1.x, header field names are strings of ASCII
characters that are compared …
```
=> Fix header field parser using case-insensitive compare

test/cbmc/proofs/findHeaderFieldParserCallback/findHeaderFieldParserCallback_harness.c, test/cbmc/proofs/findHeaderValueParserCallback/findHeaderValueParserCallback_harness.c, test/cbmc/proofs/httpParserOnBodyCallback/httpParserOnBodyCallback_harness.c, test/cbmc/proofs/httpParserOnHeaderFieldCallback/httpParserOnHeaderFieldCallback_harness.c, test/cbmc/proofs/httpParserOnHeaderValueCallback/httpParserOnHeaderValueCallback_harness.c, test/cbmc/proofs/httpParserOnStatusCallback/httpParserOnStatusCallback_harness.c, test/cbmc/sources/http_cbmc_state.c
Fixes new CBMC errors due to harnesses having additions that could overflow, potentially adding to a null pointer, as well as assumptions that did not prevent cases where pointer addition could go out of bounds. Also fixes a coverage reduction with new version.
=> Fix CBMC issues with latest version of CBMC

.github/memory_statistics_config.json, docs/doxygen/include/size_table.html
The memory estimator tool no longer special cases paths including '3rdparty' to have a 'third-party utility' tag. This fixes it and sets the tag to be more descriptive.
=> Update memory table config for tagging

test/cbmc/proofs/findHeaderFieldParserCallback/findHeaderFieldParserCallback_harness.c, test/cbmc/proofs/findHeaderOnHeaderCompleteCallback/findHeaderOnHeaderCompleteCallback_harness.c, test/cbmc/proofs/findHeaderValueParserCallback/findHeaderValueParserCallback_harness.c, test/cbmc/proofs/httpParserOnBodyCallback/httpParserOnBodyCallback_harness.c, test/cbmc/proofs/httpParserOnHeaderFieldCallback/httpParserOnHeaderFieldCallback_harness.c, test/cbmc/proofs/httpParserOnHeaderValueCallback/httpParserOnHeaderValueCallback_harness.c, test/cbmc/proofs/httpParserOnHeadersCompleteCallback/httpParserOnHeadersCompleteCallback_harness.c, test/cbmc/proofs/httpParserOnMessageBeginCallback/httpParserOnMessageBeginCallback_harness.c, test/cbmc/proofs/httpParserOnMessageCompleteCallback/httpParserOnMessageCompleteCallback_harness.c, test/cbmc/proofs/httpParserOnStatusCallback/httpParserOnStatusCallback_harness.c
The commit adds function protocols to CBMC proof harnesses for static functions exported with `--export-file-local-symbols`.  Prior to this commit, the harnesses were invoking the static function by its mangled name without declaring the mangled named, the compiler was inferring a default type for the declaration that conflicted with the type of the definition, and the linker was silently refusing to update the symbol table with the definition due to the type conflict.
=> Add function prototypes for exported functions to CBMC proof harnesses

source/core_http_client.c, test/unit-test/core_http_send_utest.c, test/unit-test/core_http_utest.c
Add response buffer length check to prevent receive zero byte with transport interface in receiveAndParseHttpResponse.
```C
static HTTPStatus_t receiveAndParseHttpResponse( const TransportInterface_t * pTransport,
HTTPResponse_t * pResponse,
const HTTPRequestHeaders_t * pRequestHeaders )
{
...
while( shouldRecv == 1U )
{
/* Receive the HTTP response data into the pResponse->pBuffer. */
currentReceived = pTransport->recv( pTransport->pNetworkContext,
pResponse->pBuffer + totalReceived,
pResponse->bufferLen - totalReceived );
```
=> Add response buffer len check

.gitmodules, README.md, test/cbmc/include/README.md, test/cbmc/proofs/Makefile-project-defines, test/cbmc/proofs/Makefile-project-targets, test/cbmc/proofs/Makefile-project-testing, test/cbmc/proofs/Makefile.common, test/cbmc/proofs/README.md, test/cbmc/proofs/findHeaderFieldParserCallback/Makefile, test/cbmc/proofs/findHeaderOnHeaderCompleteCallback/Makefile, test/cbmc/proofs/findHeaderValueParserCallback/Makefile, test/cbmc/proofs/httpParserOnBodyCallback/Makefile, test/cbmc/proofs/httpParserOnHeaderFieldCallback/Makefile, test/cbmc/proofs/httpParserOnHeaderValueCallback/Makefile, test/cbmc/proofs/httpParserOnHeadersCompleteCallback/Makefile, test/cbmc/proofs/httpParserOnMessageBeginCallback/Makefile, test/cbmc/proofs/httpParserOnMessageCompleteCallback/Makefile, test/cbmc/proofs/httpParserOnStatusCallback/Makefile, test/cbmc/proofs/lib/summarize.py, test/cbmc/proofs/run-cbmc-proofs.py, test/cbmc/sources/README.md, test/cbmc/stubs/README.md
This PR:
- changes the SPDX identifier in CBMC proof Makefile from Apache-2.0 to MIT-0
- introduces updates to the files related to the CBMC starter kit (this was accomplished by running `cbmc-starter-kit-update`).
- removes 2 .git submodules (this was accomplished by running `cbmc-starter-kit-update --remove-starter-kit-submodule --remove-litani-submodule`). symlinks to files present in the CBMC starter-kit submodule are no longer present Additionally, a user will have to install litani (instructions [here](https://github.com/awslabs/aws-build-accumulator#installation)) in order to run CBMC proofs locally. litani is present in the CI system that executes the CBMC proofs.
- updates the `README` to include a section on CBMC.
=> Update CBMC starter kit

MISRA.md, docs/doxygen/include/size_table.md, lexicon.txt, source/core_http_client.c, source/include/core_http_client_private.h, test/CMakeLists.txt, tools/coverity/misra.config
=> MISRA Compliance Update

MISRA.md, source/core_http_client.c, source/include/core_http_client_private.h, test/unit-test/core_http_utest.c
A team member ran into an issue when compiling tests linking with this repo.
Reverting a change we had come up with to a MISRA compliant version of this original function.
=> Revert "unsigned char" parameter to caseInsensitiveStringCmp()

.github/workflows/ci.yml, test/cbmc/proofs/HTTPClient_AddHeader/Makefile, test/cbmc/proofs/HTTPClient_AddRangeHeader/Makefile, test/cbmc/proofs/HTTPClient_InitializeRequestHeaders/Makefile, test/cbmc/proofs/HTTPClient_InitializeRequestHeaders/cbmc-proof.txt, test/cbmc/proofs/HTTPClient_ReadHeader/Makefile, test/cbmc/proofs/HTTPClient_Send/Makefile, test/cbmc/proofs/HTTPClient_strerror/Makefile, test/cbmc/proofs/findHeaderFieldParserCallback/Makefile, test/cbmc/proofs/findHeaderOnHeaderCompleteCallback/Makefile, test/cbmc/proofs/findHeaderValueParserCallback/Makefile, test/cbmc/proofs/httpParserOnBodyCallback/Makefile, test/cbmc/proofs/httpParserOnBodyCallback/cbmc-proof.txt, test/cbmc/proofs/httpParserOnHeaderFieldCallback/Makefile, test/cbmc/proofs/httpParserOnHeaderValueCallback/Makefile, test/cbmc/proofs/httpParserOnHeadersCompleteCallback/Makefile, test/cbmc/proofs/httpParserOnMessageBeginCallback/Makefile, test/cbmc/proofs/httpParserOnMessageCompleteCallback/Makefile, test/cbmc/proofs/httpParserOnStatusCallback/Makefile, test/cbmc/proofs/lib/print_tool_versions.py, test/cbmc/proofs/lib/summarize.py, test/cbmc/proofs/run-cbmc-proofs.py
This commit adds a GitHub Action that runs the CBMC proofs upon every push and pull request. This is intended to replace the current CBMC CI.
=> Add CBMC proof-running GitHub Action

docs/doxygen/include/size_table.md, source/core_http_client.c, source/include/core_http_client.h
Support http request without HTTP_USER_AGENT_FIELD
Description
-----------
As discussed in https://github.com/aws/aws-iot-device-sdk-embedded-C/issues/1887 I have made changes to an existing demo http_demo_s3_download to generate a presigned URL instead of directly downloading the file.
I'm planning, if the changes to the submodules are accepted, to then generate a new demo called http_demo_s3_presigned_url or something like that.
You can see/test my work at https://github.com/giuspen/aws-iot-device-sdk-embedded-C/tree/GP_http_demo_s3_download_test_signature (only generate presigned URL) or https://github.com/giuspen/aws-iot-device-sdk-embedded-C/tree/GP_http_demo_s3_download_test_signature2 (download and also generate presigned URL)
Test Steps
-----------
Exact same requirements of …
=> [support presigned URL] support http request without HTTP_USER_AGENT_FIELD

docs/doxygen/include/size_table.md, source/core_http_client.c, source/include/core_http_client.h, test/cbmc/proofs/HTTPClient_Send/Makefile
Description
-----------
In this Work-In-Progress (WIP) PR, we have showcased a sample implementation that exposes the internal functions `sendHttpHeaders`, `sendHttpData`, and `receiveAndParseHttpResponse` within the coreHTTP library. Exposing these functions aims to provide developers with more control over the HTTP communication process, enabling the support for chunked body reads and writes, streaming, and other advanced HTTP functionalities which are essential for building more sophisticated applications atop coreHTTP.
Test Steps
-----------
To reproduce the changes, follow these steps:
1. Clone the branch associated with this PR.
2. Navigate to the coreHTTP library directory.
3. Compile and run the tests provided to observe the enhanced functionality enabled by exposing the mentioned …
=> Expose Internal Functions for Enhanced Usability

README.md, docs/doxygen/pages.dox
Description
-----------
Add the following function in doxygen function list
* HTTPClient_SendHttpHeaders
* HTTPClient_SendHttpData
* HTTPClient_ReceiveAndParseHttpResponse
Test Steps
-----------
These three functions should be listed in function list generated by doxygen.
Checklist:
----------
Related Issue
-----------
=> Update doxygen page

.github/.cSpellWords.txt, .github/workflows/ci.yml, source/core_http_client.c, test/CMakeLists.txt
Add compiler warning check in the CI workflow
Description
-----------
* Fix conversion compiler warning
* Update coverity_analysis target to build core_http_client.c only
* Adding the compile warning check in coverity_analysis target
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Add compiler warning check in the CI workflow

.github/workflows/ci.yml, test/unit-test/core_http_send_utest.c, test/unit-test/core_http_utest.c
Add more unit tests
Description
-----------
* Cover on_status_complete callback added in #173
* Cover HTTP_RESPONSE_DO_NOT_PARSE_BODY_FLAG added in #172 
* Cover HTTP_REQUEST_NO_USER_AGENT_FLAG add in #164
* Enforce 100% code coverage in unit test
Test Steps
-----------
Running unit test the code coverage should be 100%.
Checklist:
----------
Related Issue
-----------
#164, #172, #173
=> Add more unit tests for coverage

.github/workflows/ci.yml, test/cbmc/proofs/HTTPClient_AddHeader/HTTPClient_AddHeader_harness.c, test/cbmc/proofs/HTTPClient_AddHeader/Makefile, test/cbmc/proofs/HTTPClient_AddRangeHeader/HTTPClient_AddRangeHeader_harness.c, test/cbmc/proofs/HTTPClient_AddRangeHeader/Makefile, test/cbmc/proofs/HTTPClient_ReadHeader/HTTPClient_ReadHeader_harness.c, test/cbmc/proofs/HTTPClient_Send/HTTPClient_Send_harness.c, test/cbmc/proofs/HTTPClient_Send/Makefile, test/cbmc/proofs/Makefile.common, test/cbmc/stubs/httpHeaderStrncpy.c
Description
-----------
With CBMC v6, unwinding assertions are enabled by default, and object bits no longer need to be set at compile time. Update various build rules to use the latest template as provided with CBMC starter kit.
Test Steps
-----------
Tested in CI.
Checklist:
----------
- n/a I have modified and/or added unit-tests to cover the code changes in this Pull Request.
=> Adjust proof tooling to support CBMC v6

source/include/core_http_config_defaults.h
Clean up comment in core_http_config_defaults.h
Description
-----------
The comment for the `HTTP_RECV_RETRY_TIMEOUT_MS` config item references `HTTPClient_Send` when I think it actually applies to `HTTPClient_ReceiveAndParseHttpResponse` (based on the name and because that is where this value is used in the source). Updated the comment but feel free to close if I'm mistaken.
Test Steps
-----------
Checklist:
----------
Have a linker error that I need to debug  when trying to build the tests so haven't run those, comment change only though
Related Issue
-----------
=> Fix comment in config defaults header file
